CREATE ROLE ad_manager;
CREATE ROLE ps_manager;
CREATE ROLE pd_manager;

GRANT SELECT ON PRODUCT_USER TO pd_manager;
GRANT SELECT ON ADVERTISEMENT TO pd_manager;
GRANT SELECT ON PARTNERSHIP TO pd_manager;
GRANT ALL ON PARTNERSHIP TO ps_manager;
GRANT ALL ON ADVERTISEMENT TO ad_manager;


CREATE USER alice IDENTIFIED BY abcd1234;
CREATE USER bob IDENTIFIED BY abcd1234;
CREATE USER chris IDENTIFIED BY abcd1234;

GRANT pd_manager TO alice;
GRANT ps_manager TO bob;
GRANT ad_manager TO chris;

GRANT CREATE SESSION TO alice;
GRANT CREATE SESSION TO bob;
GRANT CREATE SESSION TO chris;

