CREATE ROLE ad_manager;
CREATE ROLE ps_manager;
CREATE ROLE pr_manager;

GRANT SELECT ON PRODUCT_USERS TO pd_manager;
GRANT SELECT ON ADVERTISEMENTS TO pd_manager;
GRANT SELECT ON PARTNERSHIPS TO pd_manager;

GRANT ALL ON PARTNERSHIPS TO pr_manager;
GRANT ALL ON ADVERTISEMENTS TO ad_manager;


CREATE USER P0001 IDENTIFIED BY abcd1234;
CREATE USER P0003 IDENTIFIED BY abcd1234;
CREATE USER P0004 IDENTIFIED BY abcd1234;

GRANT pd_manager TO P0001;
GRANT pr_manager TO P0003;
GRANT ad_manager TO P0004;

GRANT CREATE SESSION TO P0001;
GRANT CREATE SESSION TO P0003;
GRANT CREATE SESSION TO P0004;

