CREATE TABLE DEPARTMENTS 
(
  ID INT NOT NULL,
  NAME VARCHAR2(20) NOT NULL, 
  CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE EMPLOYEES 
(
  ID VARCHAR2(20) NOT NULL, 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL,
  GENDER VARCHAR2(20) NOT NULL, 
  DEARTMENT_ID NUMBER NOT NULL, 
  POSITION VARCHAR2(20) NOT NULL, 
  ACCESS_LEVEL SMALLINT NOT NULL, 
  BASE VARCHAR2(20),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEARTMENT_ID) REFERENCES DEPARTMENTS(ID)
  ENABLE 
);

CREATE TABLE PROJECT_FEEDBACK
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  FEEDBACK VARCHAR2(2000) NOT NULL, 
  IMPROVEMENT VARCHAR2(2000) NOT NULL, 
  COMPRTING_PROJ VARCHAR2(32),
  UPDATE_TIME DATE NOT NULL, 
  CONSTRAINT PROJECT_FEEDBACK_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_FEEDBACK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)

);

CREATE TABLE PROJECT_COPYWRITING
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  GROUP_TYPE NUMBER NOT NULL,
  CONTENT VARCHAR2(2000) NOT NULL, 
  PICTURE BLOB,
  UPDATE_TIME DATE NOT NULL, 
  CONSTRAINT PROJECT_COPYWRITING_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_COPYWRITING FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);

CREATE TABLE EVENT_PLANNING
(
  ID INT NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  EVENT_TYPE VARCHAR2(20) NOT NULL,
  PURPOSE VARCHAR2(2000) NOT NULL, 
  EVENT_OBJECT VARCHAR2(20),
  BUDGET NUMBER NOT NULL,
  EVENT_LOCATION VARCHAR2(200) NOT NULL,
  FINAL_TIME DATE NOT NULL, 
  CONSTRAINT EVENT_PLANNING_PK PRIMARY KEY (ID),
  CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID) 
);