CREATE USER ad_manager IDENTIFIED BY abcd1234;
CREATE USER ps_manager IDENTIFIED BY abcd1234;
CREATE USER pd_manager IDENTIFIED BY abcd1234;

GRANT CREATE SESSION TO ad_manager;
GRANT CREATE SESSION TO ps_manager;
GRANT CREATE SESSION TO pd_manager;


GRANT SELECT ON PRODUCT_USER TO pd_manager;
GRANT SELECT ON ADVERTISEMENT TO pd_manager;
GRANT SELECT ON PARTNERSHIP TO pd_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON PARTNERSHIP TO ps_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON ADVERTISEMENT TO ad_manager;