CREATE TABLE PRODUCT_USER 
(
  ID INT NOT NULL 
, PROJECT_ID INT NOT NULL 
, FIRST_NAME VARCHAR2(20) NOT NULL 
, LAST_NAME VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(32) NOT NULL 
, ADDRESS VARCHAR2(32) NOT NULL 
, DOB DATE NOT NULL 
, GENDER VARCHAR2(20) NOT NULL 
, TAGS VARCHAR2(20) 
, CONSTRAINT PRODUCT_USER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE ADVERTISEMENT 
(
  ID INT NOT NULL 
, PRODUCT_ID INT NOT NULL 
, MANAGER INT NOT NULL 
, EXPENSE DECIMAL NOT NULL 
, TARGET VARCHAR2(20) NOT NULL 
, CLICK_RATE DECIMAL NOT NULL 
, CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE PARTNERSHIP 
(
  ID INT NOT NULL 
, PRODUCT_ID INT NOT NULL 
, COMPANY VARCHAR2(20) NOT NULL 
, MANAGER INT NOT NULL 
, COUNTRY VARCHAR2(20) NOT NULL 
, PERIOD INT NOT NULL 
, CONSTRAINT PARTNERSHIP_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);




