--- 创建hr用户
CREATE ROLE hrbp;
CREATE ROLE hr_manager;

GRANT ALL ON HR_PERSON_DETAILS TO hrbp;
GRANT ALL ON HR_PERSON_DETAILS TO hrbp;
GRANT ALL ON HR_PERSON_DETAILS TO hrbp;
GRANT ALL ON HR_PERSON_DETAILS TO hrbp;

GRANT ALL ON HR_PERSON_DETAILS TO hr_manager;
GRANT ALL ON HR_PERSON_DETAILS TO hr_manager;
GRANT ALL ON HR_PERSON_DETAILS TO hr_manager;
GRANT ALL ON HR_PERSON_DETAILS TO hr_manager;


GRANT ALL ON HR_ATTENDANCE TO hrbp;
GRANT ALL ON HR_ATTENDANCE TO hrbp;
GRANT ALL ON HR_ATTENDANCE TO hrbp;
GRANT ALL ON HR_ATTENDANCE TO hrbp;


GRANT ALL ON HR_ATTENDANCE TO hr_manager;
GRANT ALL ON HR_ATTENDANCE TO hr_manager;
GRANT ALL ON HR_ATTENDANCE TO hr_manager;
GRANT ALL ON HR_ATTENDANCE TO hr_manager;


GRANT ALL ON HR_LEAVE TO hrbp;
GRANT ALL ON HR_LEAVE TO hrbp;
GRANT ALL ON HR_LEAVE TO hrbp;
GRANT ALL ON HR_LEAVE TO hrbp;


GRANT ALL ON HR_LEAVE TO hr_manager;
GRANT ALL ON HR_LEAVE TO hr_manager;
GRANT ALL ON HR_LEAVE TO hr_manager;
GRANT ALL ON HR_LEAVE TO hr_manager;

CREATE USER HR10001 IDENTIFIED BY abcd1234;
CREATE USER HR10002 IDENTIFIED BY abcd1234;

GRANT hrbp to HR10001;
GRANT hr_manager to HR10002;

GRANT CREATE SESSION TO HR10001;
GRANT CREATE SESSION TO HR10002;
