CREATE TABLE DEPARTMENTS 
(
  ID NUMBER NOT NULL,
  NAME VARCHAR2(20) NOT NULL, 
  CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE EMPLOYEES 
(
  ID NUMBER NOT NULL, 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL,
  GENDER VARCHAR2(20) NOT NULL, 
  DEARTMENT_ID NUMBER NOT NULL, 
  POSITION VARCHAR2(20) NOT NULL, 
  J_LEVEL SMALLINT NOT NULL, 
  BASE VARCHAR2(20),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEARTMENT_ID) REFERENCES DEPARTMENTS(ID)
  ENABLE 
);


CREATE TABLE PRODUCT_USERS
(
  ID NUMBER NOT NULL 
  PROJECT_ID INT NOT NULL 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL, 
  EMAIL VARCHAR2(32) NOT NULL,
  ADDRESS VARCHAR2(32) NOT NULL, 
  DOB DATE NOT NULL, 
  GENDER VARCHAR2(20) NOT NULL, 
  TAGS VARCHAR2(20), 
  CONSTRAINT PRODUCT_USER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PRODUCT_USER FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
  ENABLE 
);

CREATE TABLE ADVERTISEMENTS 
(
  ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  MANAGER_ID INT NOT NULL,
  EXPENSE DECIMAL NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  CLICK_RATE DECIMAL NOT NULL, 
  CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID),
  ENABLE 
);


CREATE TABLE PARTNERSHIP 
(
  ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  COMPANY VARCHAR2(20) NOT NULL, 
  MANAGER_ID INT NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  LENGTH INT NOT NULL, 
  CONSTRAINT PARTNERSHIP_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE(ID),
  ENABLE 
);









