CREATE TABLE DEPARTMENTS 
(
  ID INT NOT NULL,
  NAME VARCHAR2(20) NOT NULL, 
  CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE EMPLOYEES 
(
  ID VARCHAR2(20) NOT NULL, 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL,
  GENDER VARCHAR2(20) NOT NULL, 
  DEPARTMENT_ID NUMBER NOT NULL, 
  POSITION VARCHAR2(20) NOT NULL, 
  ACCESS_LEVEL VARCHAR2(2) NOT NULL, 
  BASE VARCHAR2(20),
  CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID)
  ENABLE 
);


CREATE TABLE PROJECT_USERS
(
  ID INT NOT NULL, 
  PROJECT_ID INT NOT NULL, 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL, 
  EMAIL VARCHAR2(32) NOT NULL,
  TAGS VARCHAR2(20), 
  CONSTRAINT PROJECT_USER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_USER FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

CREATE TABLE ADVERTISEMENTS 
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  MANAGER_ID VARCHAR2(20) NOT NULL,
  EXPENSE DECIMAL NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_AD FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE_AD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);


CREATE TABLE PARTNERSHIPS 
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  COMPANY VARCHAR2(20) NOT NULL, 
  MANAGER_ID VARCHAR2(20) NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  LENGTH INT NOT NULL, 
  CONSTRAINT PARTNERSHIP_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_PS FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE_PS FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);









