CREATE TABLE PROJECT_USERS
(
  ID INT NOT NULL, 
  PROJECT_ID INT NOT NULL, 
  FIRST_NAME VARCHAR2(20) NOT NULL, 
  LAST_NAME VARCHAR2(20) NOT NULL, 
  EMAIL VARCHAR2(32) NOT NULL,
  TAGS VARCHAR2(20), 
  CONFIDENTIAL VARCHAR2 (5) CHECK (CONFIDENTIAL IN ('true', 'false')) NOT NULL,
  CONSTRAINT PROJECT_USER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_USER FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);

CREATE TABLE PROJECTS 
(
  ID INT NOT NULL,
  NAME VARCHAR2(32) UNIQUE NOT NULL,
  DESCRIPTION CLOB NOT NULL,
  DUE DATE NOT NULL,
  EST_MEMBER_NUM NUMBER(3) NOT NULL,
  STATUS VARCHAR2(10) CHECK (STATUS IN ('planned', 'ongoing', 'finished')) NOT NULL,
  SPECIAL VARCHAR2(5) CHECK (SPECIAL IN ('true', 'false')) NOT NULL,
  MANAGER_ID VARCHAR2(20) NOT NULL,
  CONSTRAINT projects_id_pk PRIMARY KEY (id),
  CONSTRAINT FK_EMPLOYEES_PROJECT FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);

CREATE TABLE DEPARTMENTS 
(
  ID INT NOT NULL,
  NAME VARCHAR2(20) NOT NULL, 
  CONSTRAINT DEPARTMENT_PK PRIMARY KEY (ID) 
  ENABLE 
);





CREATE TABLE ADVERTISEMENTS 
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  MANAGER_ID VARCHAR2(20) NOT NULL,
  EXPENSE DECIMAL NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  CONSTRAINT ADVERTISEMENT_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_AD FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE_AD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);



CREATE TABLE PARTNERSHIPS 
(
  ID INT NOT NULL,
  PROJECT_ID INT NOT NULL,
  COMPANY VARCHAR2(20) NOT NULL, 
  MANAGER_ID VARCHAR2(20) NOT NULL,
  COUNTRY VARCHAR2(20) NOT NULL, 
  LENGTH INT NOT NULL, 
  DISCLOSED VARCHAR2(5) CHECK (DISCLOSED IN ('true', 'false')) NOT NULL,
  SUING VARCHAR2(5) CHECK (SUING IN ('true', 'false')) NOT NULL,
  CONSTRAINT PARTNERSHIP_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PROJECT_PS FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID),
  CONSTRAINT FK_EMPLOYEE_PS FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);


