-- create roles for SEW
CREATE ROLE SWE_FE_1;
CREATE ROLE SWE_FE_2;
CREATE ROLE SWE_FE_3;

CREATE ROLE SWE_BE_1;
CREATE ROLE SWE_BE_2;
CREATE ROLE SWE_BE_3;

CREATE ROLE SWE_TEST_1;
CREATE ROLE SWE_TEST_2;
CREATE ROLE SWE_TEST_3;
