CREATE ROLE ad_manager;
CREATE ROLE ps_manager;
CREATE ROLE pr_manager; 
CREATE ROLE ds;


GRANT SELECT ON EMPLOYEES TO ad_manager;
GRANT SELECT ON EMPLOYEES TO pr_manager;
GRANT SELECT ON EMPLOYEES TO ad_manager;
GRANT SELECT ON EMPLOYEES TO pd_manager;


GRANT SELECT, UPDATE (tags) ON PROJECT_USERS TO ds;
GRANT SELECT ON PROJECTS TO ds;

GRANT SELECT ON PROJECT_USERS TO pd_manager;
GRANT SELECT ON ADVERTISEMENTS TO pd_manager;
GRANT SELECT ON PARTNERSHIPS TO pd_manager;
GRANT SELECT, UPDATE ON PROJECTS TO pd_manager;

GRANT SELECT ON PROJECTS TO pr_manager;
GRANT SELECT ON PROJECTS TO ad_manager;


GRANT ALL ON PARTNERSHIPS TO pr_manager;
GRANT ALL ON ADVERTISEMENTS TO ad_manager;



CREATE USER P0001 IDENTIFIED BY abcd1234;
CREATE USER P0002 IDENTIFIED BY abcd1234;
CREATE USER P0003 IDENTIFIED BY abcd1234;
CREATE USER P0004 IDENTIFIED BY abcd1234;

GRANT pd_manager TO P0001;
GRANT ds TO P0002;
GRANT pr_manager TO P0003;
GRANT ad_manager TO P0004;




GRANT CREATE SESSION TO P0001;
GRANT CREATE SESSION TO P0002;
GRANT CREATE SESSION TO P0003;
GRANT CREATE SESSION TO P0004;

