CREATE TABLE HR_PERSON_DETAILS
(
  ID VARCHAR2(20) NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(20) ,
  TELEPHONE VARCHAR2(20) ,
  EDUCATION_BG VARCHAR2(20),
  HIREDATE  DATE,
  CONSTRAINT HR_PERSON_DETAILS_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE HR_ATTENDANCE
(
  ID VARCHAR2(20) NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  SIGN_IN_TIME TIMESTAMP , 
  SIGN_OUT_TIME TIMESTAMP,
  CONSTRAINT HR_ATTENDANCE_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE HR_LEAVE
(
  ID VARCHAR2(20) NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  FROM_TIME TIMESTAMP , 
  TO_TIME TIMESTAMP,
  CONSTRAINT HR_LEAVE_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE ACCOUNTING_SALARY_HISTORY
(
  ID VARCHAR2(20) NOT NULL,
  EMPLOYEE_ID VARCHAR2(20) NOT NULL,
  TIME DATE,
  JOB_PERFORMANCE FLOAT,
  BASESALARY FLOAT,
  BONUS FLOAT,
  SUBSIDY FLOAT,
  TOTAL_SALARY FLOAT,
  CONSTRAINT  ACCOUNTING_SALARY_HISTORY_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE ADMINISTRATION_FOOD
(
  ID VARCHAR2(20) NOT NULL,
  FOOD_TIME DATE,
  ITEMS VARCHAR2(20),
  ITEM_NUMBER INT,
  BASE VARCHAR2(20),
  STATUS VARCHAR2(20),
  CONSTRAINT  ADMINISTRATION_FOOD_PK PRIMARY KEY (ID) 
  ENABLE 
);



CREATE TABLE ADMINISTRATION_CONFERENCE
(
  ID VARCHAR2(20) NOT NULL,
  BEGIN_TIME TIMESTAMP,
  END_TIME TIMESTAMP,
  CONFERENCE_ROOM VARCHAR2(20),
  REASON VARCHAR2(40),
  APPLY_PERSON VARCHAR2(20) NOT NULL,
  BASE VARCHAR2(20),
  CONSTRAINT  ADMINISTRATION_CONFERENCE_PK PRIMARY KEY (ID) 
  ENABLE 
);


CREATE TABLE ADMINISTRATION_PROPERTY
(
  PROPERTY_ID VARCHAR2(20) NOT NULL,
  ITEM VARCHAR2(20),
  PURCHASE_TIME DATE,
  AMOUNT FLOAT,
  BASE VARCHAR2(20),
  STATUS VARCHAR2(20),
  CONSTRAINT  ADMINISTRATION_PROPERTY_PK PRIMARY KEY (PROPERTY_ID) 
  ENABLE 
);



