GRANT EXECUTE ON sa_components TO cs5322 WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO cs5322 WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO cs5322 WITH GRANT OPTION;
GRANT EXECUTE ON sa_label_admin TO cs5322 WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO cs5322 WITH GRANT OPTION;
GRANT EXECUTE ON sa_audit_admin TO cs5322 WITH GRANT OPTION;

GRANT LBAC_DBA TO cs5322;
GRANT EXECUTE ON sa_sysdba TO cs5322;
GRANT EXECUTE ON to_lbac_data_label TO cs5322;

GRANT CONNECT, SDE_BE_1 TO D0001 IDENTIFIED BY password;
GRANT CONNECT, SDE_BE_2 TO D0002 IDENTIFIED BY password;
GRANT CONNECT, SDE_BE_3 TO D0003 IDENTIFIED BY password;
GRANT CONNECT, SDE_FE_1 TO D0004 IDENTIFIED BY password;
GRANT CONNECT, SDE_FE_2 TO D0005 IDENTIFIED BY password;
GRANT CONNECT, SDE_FE_3 TO D0006 IDENTIFIED BY password;
GRANT CONNECT, SDE_TE_1 TO D0007 IDENTIFIED BY password;
GRANT CONNECT, SDE_TE_2 TO D0008 IDENTIFIED BY password;
GRANT CONNECT, SDE_TE_3 TO D0009 IDENTIFIED BY password;
